// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: experience.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countExperience = `-- name: CountExperience :one
SELECT count(*) FROM experience
`

func (q *Queries) CountExperience(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countExperience)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExperience = `-- name: CreateExperience :one
INSERT INTO experience (id, kind, organization_mn, organization_en, position_mn, position_en,
                        description_mn, description_en, start_date, end_date, published)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, kind, organization_mn, organization_en, position_mn, position_en, description_mn, description_en, start_date, end_date, published, created_at, updated_at
`

type CreateExperienceParams struct {
	ID             uuid.UUID  `json:"id"`
	Kind           string     `json:"kind"`
	OrganizationMn string     `json:"organization_mn"`
	OrganizationEn string     `json:"organization_en"`
	PositionMn     string     `json:"position_mn"`
	PositionEn     string     `json:"position_en"`
	DescriptionMn  string     `json:"description_mn"`
	DescriptionEn  string     `json:"description_en"`
	StartDate      time.Time  `json:"start_date"`
	EndDate        *time.Time `json:"end_date"`
	Published      bool       `json:"published"`
}

func (q *Queries) CreateExperience(ctx context.Context, arg CreateExperienceParams) (Experience, error) {
	row := q.db.QueryRow(ctx, createExperience,
		arg.ID,
		arg.Kind,
		arg.OrganizationMn,
		arg.OrganizationEn,
		arg.PositionMn,
		arg.PositionEn,
		arg.DescriptionMn,
		arg.DescriptionEn,
		arg.StartDate,
		arg.EndDate,
		arg.Published,
	)
	var i Experience
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.OrganizationMn,
		&i.OrganizationEn,
		&i.PositionMn,
		&i.PositionEn,
		&i.DescriptionMn,
		&i.DescriptionEn,
		&i.StartDate,
		&i.EndDate,
		&i.Published,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExperience = `-- name: DeleteExperience :execrows
DELETE FROM experience WHERE id = $1
`

func (q *Queries) DeleteExperience(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExperience, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listExperience = `-- name: ListExperience :many
SELECT id, kind, organization_mn, organization_en, position_mn, position_en, description_mn, description_en, start_date, end_date, published, created_at, updated_at FROM experience
ORDER BY start_date DESC, created_at, id
`

func (q *Queries) ListExperience(ctx context.Context) ([]Experience, error) {
	rows, err := q.db.Query(ctx, listExperience)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Experience
	for rows.Next() {
		var i Experience
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.OrganizationMn,
			&i.OrganizationEn,
			&i.PositionMn,
			&i.PositionEn,
			&i.DescriptionMn,
			&i.DescriptionEn,
			&i.StartDate,
			&i.EndDate,
			&i.Published,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedExperience = `-- name: ListPublishedExperience :many
SELECT id, kind, organization_mn, organization_en, position_mn, position_en, description_mn, description_en, start_date, end_date, published, created_at, updated_at FROM experience
WHERE published
ORDER BY start_date DESC, created_at, id
`

func (q *Queries) ListPublishedExperience(ctx context.Context) ([]Experience, error) {
	rows, err := q.db.Query(ctx, listPublishedExperience)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Experience
	for rows.Next() {
		var i Experience
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.OrganizationMn,
			&i.OrganizationEn,
			&i.PositionMn,
			&i.PositionEn,
			&i.DescriptionMn,
			&i.DescriptionEn,
			&i.StartDate,
			&i.EndDate,
			&i.Published,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExperience = `-- name: UpdateExperience :one
UPDATE experience
SET kind = $2, organization_mn = $3, organization_en = $4, position_mn = $5, position_en = $6,
    description_mn = $7, description_en = $8, start_date = $9, end_date = $10, published = $11,
    updated_at = now()
WHERE id = $1
RETURNING id, kind, organization_mn, organization_en, position_mn, position_en, description_mn, description_en, start_date, end_date, published, created_at, updated_at
`

type UpdateExperienceParams struct {
	ID             uuid.UUID  `json:"id"`
	Kind           string     `json:"kind"`
	OrganizationMn string     `json:"organization_mn"`
	OrganizationEn string     `json:"organization_en"`
	PositionMn     string     `json:"position_mn"`
	PositionEn     string     `json:"position_en"`
	DescriptionMn  string     `json:"description_mn"`
	DescriptionEn  string     `json:"description_en"`
	StartDate      time.Time  `json:"start_date"`
	EndDate        *time.Time `json:"end_date"`
	Published      bool       `json:"published"`
}

func (q *Queries) UpdateExperience(ctx context.Context, arg UpdateExperienceParams) (Experience, error) {
	row := q.db.QueryRow(ctx, updateExperience,
		arg.ID,
		arg.Kind,
		arg.OrganizationMn,
		arg.OrganizationEn,
		arg.PositionMn,
		arg.PositionEn,
		arg.DescriptionMn,
		arg.DescriptionEn,
		arg.StartDate,
		arg.EndDate,
		arg.Published,
	)
	var i Experience
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.OrganizationMn,
		&i.OrganizationEn,
		&i.PositionMn,
		&i.PositionEn,
		&i.DescriptionMn,
		&i.DescriptionEn,
		&i.StartDate,
		&i.EndDate,
		&i.Published,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
