// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type AdminAuditLog struct {
	ID        uuid.UUID  `json:"id"`
	AdminID   *uuid.UUID `json:"admin_id"`
	Event     string     `json:"event"`
	Ip        *string    `json:"ip"`
	UserAgent *string    `json:"user_agent"`
	CreatedAt time.Time  `json:"created_at"`
}

type AdminUser struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}

type Experience struct {
	ID             uuid.UUID  `json:"id"`
	Kind           string     `json:"kind"`
	OrganizationMn string     `json:"organization_mn"`
	OrganizationEn string     `json:"organization_en"`
	PositionMn     string     `json:"position_mn"`
	PositionEn     string     `json:"position_en"`
	DescriptionMn  string     `json:"description_mn"`
	DescriptionEn  string     `json:"description_en"`
	StartDate      time.Time  `json:"start_date"`
	EndDate        *time.Time `json:"end_date"`
	Published      bool       `json:"published"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
}

type Lead struct {
	ID         uuid.UUID   `json:"id"`
	Name       string      `json:"name"`
	Email      string      `json:"email"`
	Message    string      `json:"message"`
	Locale     string      `json:"locale"`
	SourcePage *string     `json:"source_page"`
	Ip         *netip.Addr `json:"ip"`
	UserAgent  *string     `json:"user_agent"`
	CreatedAt  time.Time   `json:"created_at"`
}

type LoginAttempt struct {
	Email         string     `json:"email"`
	FailedCount   int32      `json:"failed_count"`
	LockedUntil   *time.Time `json:"locked_until"`
	LastFailureAt time.Time  `json:"last_failure_at"`
	Ip            string     `json:"ip"`
}

type Project struct {
	ID              uuid.UUID `json:"id"`
	Title           string    `json:"title"`
	Url             string    `json:"url"`
	DescriptionMn   string    `json:"description_mn"`
	DescriptionEn   string    `json:"description_en"`
	SortOrder       int32     `json:"sort_order"`
	Published       bool      `json:"published"`
	Logo            []byte    `json:"logo"`
	LogoContentType *string   `json:"logo_content_type"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type ProjectSummary struct {
	ID            uuid.UUID `json:"id"`
	Title         string    `json:"title"`
	Url           string    `json:"url"`
	DescriptionMn string    `json:"description_mn"`
	DescriptionEn string    `json:"description_en"`
	SortOrder     int32     `json:"sort_order"`
	Published     bool      `json:"published"`
	HasLogo       bool      `json:"has_logo"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type RefreshToken struct {
	Jti             uuid.UUID  `json:"jti"`
	AdminID         uuid.UUID  `json:"admin_id"`
	FamilyID        uuid.UUID  `json:"family_id"`
	ExpiresAt       time.Time  `json:"expires_at"`
	RevokedAt       *time.Time `json:"revoked_at"`
	FamilyExpiresAt time.Time  `json:"family_expires_at"`
	ReplacedBy      *uuid.UUID `json:"replaced_by"`
}
