// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const clearProjectLogo = `-- name: ClearProjectLogo :execrows
UPDATE projects
SET logo = NULL, logo_content_type = NULL, updated_at = now()
WHERE id = $1
`

func (q *Queries) ClearProjectLogo(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, clearProjectLogo, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countProjects = `-- name: CountProjects :one
SELECT count(*) FROM projects
`

func (q *Queries) CountProjects(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProjects)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :exec
INSERT INTO projects (id, title, url, description_mn, description_en, published, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, (SELECT COALESCE(MAX(sort_order) + 1, 0) FROM projects))
`

type CreateProjectParams struct {
	ID            uuid.UUID `json:"id"`
	Title         string    `json:"title"`
	Url           string    `json:"url"`
	DescriptionMn string    `json:"description_mn"`
	DescriptionEn string    `json:"description_en"`
	Published     bool      `json:"published"`
}

// Appends at the end. Two creates at the same moment can share a sort_order; the tiebreak in the
// list queries keeps that harmless, and the next reorder fixes it.
func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) error {
	_, err := q.db.Exec(ctx, createProject,
		arg.ID,
		arg.Title,
		arg.Url,
		arg.DescriptionMn,
		arg.DescriptionEn,
		arg.Published,
	)
	return err
}

const deleteProject = `-- name: DeleteProject :execrows
DELETE FROM projects WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProject, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProject = `-- name: GetProject :one
SELECT id, title, url, description_mn, description_en, sort_order, published, has_logo, created_at, updated_at FROM project_summaries WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id uuid.UUID) (ProjectSummary, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i ProjectSummary
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Url,
		&i.DescriptionMn,
		&i.DescriptionEn,
		&i.SortOrder,
		&i.Published,
		&i.HasLogo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectLogo = `-- name: GetProjectLogo :one
SELECT logo, logo_content_type FROM projects
WHERE id = $1 AND logo IS NOT NULL
`

type GetProjectLogoRow struct {
	Logo            []byte  `json:"logo"`
	LogoContentType *string `json:"logo_content_type"`
}

func (q *Queries) GetProjectLogo(ctx context.Context, id uuid.UUID) (GetProjectLogoRow, error) {
	row := q.db.QueryRow(ctx, getProjectLogo, id)
	var i GetProjectLogoRow
	err := row.Scan(&i.Logo, &i.LogoContentType)
	return i, err
}

const importProject = `-- name: ImportProject :exec
INSERT INTO projects (id, title, url, description_mn, description_en, published, sort_order, logo,
                      logo_content_type)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type ImportProjectParams struct {
	ID              uuid.UUID `json:"id"`
	Title           string    `json:"title"`
	Url             string    `json:"url"`
	DescriptionMn   string    `json:"description_mn"`
	DescriptionEn   string    `json:"description_en"`
	Published       bool      `json:"published"`
	SortOrder       int32     `json:"sort_order"`
	Logo            []byte    `json:"logo"`
	LogoContentType *string   `json:"logo_content_type"`
}

func (q *Queries) ImportProject(ctx context.Context, arg ImportProjectParams) error {
	_, err := q.db.Exec(ctx, importProject,
		arg.ID,
		arg.Title,
		arg.Url,
		arg.DescriptionMn,
		arg.DescriptionEn,
		arg.Published,
		arg.SortOrder,
		arg.Logo,
		arg.LogoContentType,
	)
	return err
}

const listProjects = `-- name: ListProjects :many
SELECT id, title, url, description_mn, description_en, sort_order, published, has_logo, created_at, updated_at FROM project_summaries
ORDER BY sort_order, created_at, id
`

// created_at and id break ties, so two rows with one sort_order keep a stable order.
func (q *Queries) ListProjects(ctx context.Context) ([]ProjectSummary, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectSummary
	for rows.Next() {
		var i ProjectSummary
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Url,
			&i.DescriptionMn,
			&i.DescriptionEn,
			&i.SortOrder,
			&i.Published,
			&i.HasLogo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedProjects = `-- name: ListPublishedProjects :many
SELECT id, title, url, description_mn, description_en, sort_order, published, has_logo, created_at, updated_at FROM project_summaries
WHERE published
ORDER BY sort_order, created_at, id
`

func (q *Queries) ListPublishedProjects(ctx context.Context) ([]ProjectSummary, error) {
	rows, err := q.db.Query(ctx, listPublishedProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectSummary
	for rows.Next() {
		var i ProjectSummary
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Url,
			&i.DescriptionMn,
			&i.DescriptionEn,
			&i.SortOrder,
			&i.Published,
			&i.HasLogo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProjectIDs = `-- name: LockProjectIDs :many
SELECT id FROM projects FOR UPDATE
`

// FOR UPDATE holds off a concurrent edit or delete until the reorder commits.
func (q *Queries) LockProjectIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, lockProjectIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProjectLogo = `-- name: SetProjectLogo :execrows
UPDATE projects
SET logo = $2, logo_content_type = $3, updated_at = now()
WHERE id = $1
`

type SetProjectLogoParams struct {
	ID              uuid.UUID `json:"id"`
	Logo            []byte    `json:"logo"`
	LogoContentType *string   `json:"logo_content_type"`
}

// updated_at moves too: it is the cache-busting version in every logo URL.
func (q *Queries) SetProjectLogo(ctx context.Context, arg SetProjectLogoParams) (int64, error) {
	result, err := q.db.Exec(ctx, setProjectLogo, arg.ID, arg.Logo, arg.LogoContentType)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setProjectSortOrder = `-- name: SetProjectSortOrder :exec
UPDATE projects SET sort_order = $2 WHERE id = $1
`

type SetProjectSortOrderParams struct {
	ID        uuid.UUID `json:"id"`
	SortOrder int32     `json:"sort_order"`
}

// updated_at stays: moving a project does not change its logo.
func (q *Queries) SetProjectSortOrder(ctx context.Context, arg SetProjectSortOrderParams) error {
	_, err := q.db.Exec(ctx, setProjectSortOrder, arg.ID, arg.SortOrder)
	return err
}

const updateProject = `-- name: UpdateProject :execrows
UPDATE projects
SET title = $2, url = $3, description_mn = $4, description_en = $5, published = $6,
    updated_at = now()
WHERE id = $1
`

type UpdateProjectParams struct {
	ID            uuid.UUID `json:"id"`
	Title         string    `json:"title"`
	Url           string    `json:"url"`
	DescriptionMn string    `json:"description_mn"`
	DescriptionEn string    `json:"description_en"`
	Published     bool      `json:"published"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateProject,
		arg.ID,
		arg.Title,
		arg.Url,
		arg.DescriptionMn,
		arg.DescriptionEn,
		arg.Published,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
