/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as SplatRouteImport } from './../routes/$'
import { Route as AdminRouteImport } from './../routes/admin'
import { Route as DocsRouteImport } from './../routes/docs'
import { Route as LoveRouteImport } from './../routes/love'
import { Route as AdminIndexRouteImport } from './../routes/admin/index'
import { Route as AdminAuthedRouteImport } from './../routes/admin/_authed'
import { Route as AdminLoginRouteImport } from './../routes/admin/login'
import { Route as AdminAuthedExperienceRouteImport } from './../routes/admin/_authed/experience'
import { Route as AdminAuthedLeadsRouteImport } from './../routes/admin/_authed/leads'
import { Route as AdminAuthedProjectsRouteImport } from './../routes/admin/_authed/projects'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoveRoute = LoveRouteImport.update({
  id: '/love',
  path: '/love',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuthedRoute = AdminAuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuthedExperienceRoute = AdminAuthedExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedLeadsRoute = AdminAuthedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedProjectsRoute = AdminAuthedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminAuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/docs': typeof DocsRoute
  '/love': typeof LoveRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/experience': typeof AdminAuthedExperienceRoute
  '/admin/leads': typeof AdminAuthedLeadsRoute
  '/admin/projects': typeof AdminAuthedProjectsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/docs': typeof DocsRoute
  '/love': typeof LoveRoute
  '/admin': typeof AdminIndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/experience': typeof AdminAuthedExperienceRoute
  '/admin/leads': typeof AdminAuthedLeadsRoute
  '/admin/projects': typeof AdminAuthedProjectsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/docs': typeof DocsRoute
  '/love': typeof LoveRoute
  '/admin/_authed': typeof AdminAuthedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/_authed/experience': typeof AdminAuthedExperienceRoute
  '/admin/_authed/leads': typeof AdminAuthedLeadsRoute
  '/admin/_authed/projects': typeof AdminAuthedProjectsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/admin'
    | '/docs'
    | '/love'
    | '/admin/login'
    | '/admin/'
    | '/admin/experience'
    | '/admin/leads'
    | '/admin/projects'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/docs'
    | '/love'
    | '/admin'
    | '/admin/login'
    | '/admin/experience'
    | '/admin/leads'
    | '/admin/projects'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/admin'
    | '/docs'
    | '/love'
    | '/admin/_authed'
    | '/admin/login'
    | '/admin/'
    | '/admin/_authed/experience'
    | '/admin/_authed/leads'
    | '/admin/_authed/projects'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AdminRoute: typeof AdminRouteWithChildren
  DocsRoute: typeof DocsRoute
  LoveRoute: typeof LoveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/love': {
      id: '/love'
      path: '/love'
      fullPath: '/love'
      preLoaderRoute: typeof LoveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_authed': {
      id: '/admin/_authed'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_authed/experience': {
      id: '/admin/_authed/experience'
      path: '/experience'
      fullPath: '/admin/experience'
      preLoaderRoute: typeof AdminAuthedExperienceRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/leads': {
      id: '/admin/_authed/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminAuthedLeadsRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/projects': {
      id: '/admin/_authed/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminAuthedProjectsRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
  }
}

interface AdminAuthedRouteChildren {
  AdminAuthedExperienceRoute: typeof AdminAuthedExperienceRoute
  AdminAuthedLeadsRoute: typeof AdminAuthedLeadsRoute
  AdminAuthedProjectsRoute: typeof AdminAuthedProjectsRoute
}

const AdminAuthedRouteChildren: AdminAuthedRouteChildren = {
  AdminAuthedExperienceRoute: AdminAuthedExperienceRoute,
  AdminAuthedLeadsRoute: AdminAuthedLeadsRoute,
  AdminAuthedProjectsRoute: AdminAuthedProjectsRoute,
}

const AdminAuthedRouteWithChildren = AdminAuthedRoute._addFileChildren(
  AdminAuthedRouteChildren,
)

interface AdminRouteChildren {
  AdminAuthedRoute: typeof AdminAuthedRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuthedRoute: AdminAuthedRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AdminRoute: AdminRouteWithChildren,
  DocsRoute: DocsRoute,
  LoveRoute: LoveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
